---
id: 62ebd404-4647-41ba-bc1d-8130d3c288fa
---
sequenceDiagram

    Main ->> FoodTruck: generate HTML
    
    FoodTruck ->> Entrees: Generate entree option
    Entrees --> FoodTruck: Here are some radio buttons

    FoodTruck->>Vegetables: Generate vegetable options
    Vegetables-->>FoodTruck: Here are some radio buttons

    FoodTruck->>Sides: Generate Side options
    Sides-->>FoodTruck: Here are some radio buttons

    FoodTruck->>Button: Generate a button
    Button-->>FoodTruck: Here is a button

    FoodTruck->>Purchased: Generate purchased meals HTML
    Purchased-->>FoodTruck: Here is some HTML

    Note over FoodTruck: Render HTML

    FoodTruck -->> Main: Here is some HTML

    Entrees ->> TransientState: option was clicked update state

    Sides ->> TransientState: option was clicked update state

    Vegetables ->> TransientState: option was clicked update state

    Button ->> TransientState: Button was pressed, send info to API

    TransientState->>API: Save this dinner order

    API-->>TransientState: Order saved

    Note over TransientState: Reset transient data

    Button ->> Main: Sends Event listener

    Note over Main: Hears event and re renders HTML